language: ruby
bundler_args: --without development

branches:
  only:
    - master

rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode

before_script: "./script/ci/before.sh"

script: "bundle exec rake spec"


