Models:
 - name: Maintenance 
   bucketname: neworleansdata
   filename: INAP Validated Address Data entry sheet 2012.xlsx
   column_map: # db column => excel 
      house_num: Number
      street_name: Street
      street_type: Accessory
      program_name: Program
# - name: Demolition
#   bucketname: neworleansdata
#   filename: NORA Validated_Demo_DataEntry_2012.xlsx
#   column_map: 
#      house_num: house_num
#      street_name: street_name
#      street_type: street_type
#      program_name: program_name
#
# - name: Demolition
#   bucketname: neworleansdata
#   filename: FEMA Validated_Demo_DataEntry_2012_January.xlsx
#   column_map: 
#      house_num: house_num
#      street_name: street_name
#      street_type: street_type
#      program_name: program_name